# Generated by Django 5.1.4 on 2025-11-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NCM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField("código", max_length=20, unique=True)),
                ("description", models.TextField("descrição")),
                (
                    "national_tax",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="imposto nacional",
                    ),
                ),
                (
                    "import_tax",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="imposto importação",
                    ),
                ),
                (
                    "state_tax",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="imposto estadual",
                    ),
                ),
                (
                    "municipal_tax",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="imposto municipal",
                    ),
                ),
                (
                    "vigency_start",
                    models.DateField(verbose_name="data de início de vigência"),
                ),
                (
                    "vigency_end",
                    models.DateField(verbose_name="data de fim de vigência"),
                ),
            ],
            options={
                "ordering": ["code"],
                "verbose_name": "NCM",
                "verbose_name_plural": "NCMs",
            },
        ),
    ]
