# Generated by Django 5.1.4 on 2025-11-15 19:41

import csv
import re
from datetime import datetime
from decimal import Decimal
from pathlib import Path

from django.db import migrations


def normalize_code(value: str) -> str:
    return re.sub(r"[\W_]+", "", value or "", flags=re.UNICODE)


def parse_decimal(raw: str) -> Decimal:
    raw = (raw or "").strip()
    if not raw:
        return Decimal("0")
    return Decimal(raw.replace(",", "."))


def parse_date(raw: str):
    raw = (raw or "").strip()
    if not raw:
        return None
    return datetime.strptime(raw, "%d/%m/%Y").date()


def load_ncms(apps, schema_editor):
    NCM = apps.get_model("nfce", "NCM")
    app_dir = Path(__file__).resolve().parents[1]
    data_file = app_dir / "data" / "TabelaIBPTaxSC25.2.G.csv"

    if not data_file.exists():
        raise FileNotFoundError(f"NCM data file not found: {data_file}")

    field_names = {field.name for field in NCM._meta.get_fields()}

    with data_file.open(encoding="utf-8") as fp:
        reader = csv.DictReader(fp)
        for row in reader:
            raw_code = normalize_code(row.get("codigo_ncm") or "")
            description = (row.get("descricao_ncm") or "").strip()

            if not raw_code or not description:
                continue

            code = raw_code.zfill(8)

            defaults = {"description": description}

            if {"national_tax", "import_tax", "state_tax", "municipal_tax"} <= field_names:
                defaults.update(
                    {
                        "national_tax": parse_decimal(row.get("nacionalfederal")),
                        "import_tax": parse_decimal(row.get("importadosfederal")),
                        "state_tax": parse_decimal(row.get("estadual")),
                        "municipal_tax": parse_decimal(row.get("municipal")),
                    }
                )

            if {"vigency_start", "vigency_end"} <= field_names:
                defaults.update(
                    {
                        "vigency_start": parse_date(row.get("vigenciainicio")),
                        "vigency_end": parse_date(row.get("vigenciafim")),
                    }
                )

            NCM.objects.update_or_create(
                code=code,
                defaults=defaults,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("nfce", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_ncms, migrations.RunPython.noop),
    ]
