# Generated by Django 5.1.4 on 2025-11-15 19:41

import json
import re
from pathlib import Path

from django.db import migrations


def normalize_code(value: str) -> str:
    return re.sub(r"[\W_]+", "", value or "", flags=re.UNICODE)


def load_ncms(apps, schema_editor):
    NCM = apps.get_model("nfce", "NCM")
    app_dir = Path(__file__).resolve().parents[1]
    data_file = app_dir / "data" / "Tabela_NCM_Vigente_20251115.json"

    if not data_file.exists():
        raise FileNotFoundError(f"NCM data file not found: {data_file}")

    with data_file.open(encoding="utf-8") as fp:
        payload = json.load(fp)

    nomenclatures = payload.get("Nomenclaturas", [])
    for item in nomenclatures:
        code = normalize_code(item.get("Codigo") or "")
        description = (item.get("Descricao") or "").strip()

        if not code or not description:
            continue

        NCM.objects.update_or_create(
            code=code,
            defaults={"description": description},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("nfce", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_ncms, migrations.RunPython.noop),
    ]
