# Generated by Django 5.1.4 on 2025-11-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfce', '0002_load_ncm_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncm',
            name='code',
            field=models.CharField(unique=True),
        ),
    ]
