# Generated by Django 5.1.4 on 2025-11-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfce', '0003_alter_ncm_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ncm',
            options={'ordering': ['code'], 'verbose_name': 'NCM', 'verbose_name_plural': 'NCMs'},
        ),
        migrations.AlterField(
            model_name='ncm',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='ncm',
            name='description',
            field=models.TextField(verbose_name='descrição'),
        ),
    ]
