# Generated by Django 5.1.4 on 2025-11-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_is_available_sidedish_is_available_and_more'),
        ('nfce', '0002_load_ncm_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidedish',
            options={'verbose_name': 'Acompanhamento', 'verbose_name_plural': 'Acompanhamentos'},
        ),
        migrations.RemoveField(
            model_name='sidedishoption',
            name='price',
        ),
        migrations.AlterField(
            model_name='dish',
            name='ncm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfce.ncm'),
        ),
    ]
