# Generated by Django 5.1.4 on 2025-11-16 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_sidedish_options_remove_sidedishoption_price_and_more'),
        ('nfce', '0004_alter_ncm_options_alter_ncm_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidedish',
            name='price',
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=6, verbose_name='cor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='department',
            field=models.CharField(choices=[('kitchen', 'Cozinha'), ('bar', 'Copa')], max_length=255, verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='disponível'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ncm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfce.ncm', verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='side_dish_options',
            field=models.ManyToManyField(blank=True, help_text='Opções de acompanhamento disponíveis ao pedir este prato.', related_name='dishes', to='menu.sidedishoption', verbose_name='opções de acompanhamento'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='sidedish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='sidedish',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='disponível'),
        ),
        migrations.AlterField(
            model_name='sidedish',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='sidedish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='sidedish',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='sidedishoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='sidedishoption',
            name='default_side_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_side_dish_options', to='menu.sidedish', verbose_name='acompanhamento padrão'),
        ),
        migrations.AlterField(
            model_name='sidedishoption',
            name='side_dishes',
            field=models.ManyToManyField(related_name='options', to='menu.sidedish', verbose_name='acompanhamentos'),
        ),
        migrations.AlterField(
            model_name='sidedishoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='sidedishoption',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
