# Generated by Django 5.1.4 on 2025-11-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_sidedish_price_alter_category_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidedishoption',
            name='default_side_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_for_side_dish_options', to='menu.sidedish', verbose_name='acompanhamento padrão'),
        ),
    ]
