# Generated by Django 5.1.4 on 2025-12-03 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_sidedishoption_default_side_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='preço')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('department', models.CharField(choices=[('kitchen', 'Cozinha'), ('bar', 'Copa')], max_length=255, verbose_name='departamento')),
                ('ncm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfce.ncm', verbose_name='NCM')),
            ],
            options={
                'verbose_name': 'Item Customizado',
                'verbose_name_plural': 'Itens Customizados',
            },
        ),
    ]
