# Generated by hand for translation support

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_dish_show_on_public_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("pt-BR", "Português (Brasil)"),
                            ("en-US", "English"),
                            ("es-ES", "Espanhol"),
                        ],
                        max_length=5,
                        verbose_name="idioma",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="menu.category",
                        verbose_name="categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tradução de Categoria",
                "verbose_name_plural": "Traduções de Categoria",
            },
        ),
        migrations.CreateModel(
            name="DishTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("pt-BR", "Português (Brasil)"),
                            ("en-US", "English"),
                            ("es-ES", "Espanhol"),
                        ],
                        max_length=5,
                        verbose_name="idioma",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="descrição"
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="menu.dish",
                        verbose_name="item do cardápio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tradução de Item do Cardápio",
                "verbose_name_plural": "Traduções de Item do Cardápio",
            },
        ),
        migrations.AddConstraint(
            model_name="categorytranslation",
            constraint=models.UniqueConstraint(
                fields=("category", "language"),
                name="unique_category_language_translation",
            ),
        ),
        migrations.AddConstraint(
            model_name="dishtranslation",
            constraint=models.UniqueConstraint(
                fields=("dish", "language"),
                name="unique_dish_language_translation",
            ),
        ),
    ]
