# Generated by Django 5.1.4 on 2025-11-15 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_is_available_sidedish_is_available_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishorder',
            name='side_dish_options',
        ),
        migrations.RemoveField(
            model_name='dishorder',
            name='default_side_dish',
        ),
        migrations.CreateModel(
            name='DishOrderSideDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dish_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_dish_selections', to='orders.dishorder')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.sidedishoption')),
                ('side_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.sidedish')),
            ],
            options={
                'unique_together': {('dish_order', 'side_dish')},
            },
        ),
        migrations.DeleteModel(
            name='DishOrderOptionSelection',
        ),
    ]
