# Generated by Django 5.1.4 on 2025-11-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ticket_alter_order_ticket_ticketsettlement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsettlement',
            old_name='additions',
            new_name='additions_value',
        ),
        migrations.RenameField(
            model_name='ticketsettlement',
            old_name='discounts',
            new_name='discounts_value',
        ),
        migrations.RenameField(
            model_name='ticketsettlement',
            old_name='final_price',
            new_name='final_value',
        ),
        migrations.RenameField(
            model_name='ticketsettlement',
            old_name='full_price',
            new_name='full_value',
        ),
    ]
