# Generated by Django 5.1.4 on 2025-11-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_additions_ticketsettlement_additions_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettlementitem',
            name='total_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
