# Generated by Django 5.1.4 on 2025-11-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ticketsettlementitem_total_taxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsettlementitem',
            name='total_taxes',
        ),
    ]
