# Generated by Django 5.1.4 on 2025-11-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_ticketsettlementitem_total_taxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketsettlement",
            name="nfce_qrcode_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketsettlement",
            name="nfce_xml",
            field=models.TextField(blank=True, null=True),
        ),
    ]
