# Generated by Django 5.1.4 on 2025-11-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_ticketsettlement_nfce_qrcode_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketsettlement",
            name="nfce_issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
