# Generated by Django 5.1.4 on 2025-12-03 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_customdish'),
        ('orders', '0009_ticketsettlement_nfce_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishorder',
            name='custom_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_orders', to='menu.customdish'),
        ),
        migrations.AlterField(
            model_name='dishorder',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_orders', to='menu.dish'),
        ),
        migrations.AddConstraint(
            model_name='dishorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_dish__isnull', True), ('dish__isnull', False)), models.Q(('custom_dish__isnull', False), ('dish__isnull', True)), _connector='OR'), name='dishorder_requires_one_item'),
        ),
    ]
