# Generated by Django 5.1.4 on 2025-12-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_dishorder_custom_dish_alter_dishorder_dish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsettlement',
            old_name='nfce_issued_at',
            new_name='nfce_authorization_datetime',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE orders_ticketsettlement "
                        "ADD COLUMN IF NOT EXISTS cancelation_xml text"
                    ),
                    reverse_sql=(
                        "ALTER TABLE orders_ticketsettlement "
                        "DROP COLUMN IF EXISTS cancelation_xml"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='ticketsettlement',
                    name='cancelation_xml',
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE orders_ticketsettlement "
                        "ADD COLUMN IF NOT EXISTS canceled boolean "
                        "DEFAULT FALSE NOT NULL"
                    ),
                    reverse_sql=(
                        "ALTER TABLE orders_ticketsettlement "
                        "DROP COLUMN IF EXISTS canceled"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='ticketsettlement',
                    name='canceled',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name='ticketsettlement',
            name='nfce_access_key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='ticketsettlement',
            name='nfce_access_key_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketsettlement',
            name='nfce_authorization_protocol',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ticketsettlement',
            name='nfce_emission_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketsettlement',
            name='nfce_emitter_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketsettlement',
            name='nfce_emitter_uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ticketsettlement',
            name='nfce_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='ticketsettlement',
            name='nfce_series',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
