# Generated by Django 5.1.4 on 2025-12-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_ticket_is_outside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsettlement',
            name='canceled',
            field=models.BooleanField(default=True),
        ),
    ]
