# Generated by Codex on 2025-??
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_ticketsettlement_canceled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketsettlement",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
