# Generated by Django 5.1.4 on 2025-12-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_update_ticket_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettlementitem',
            name='charged_half_portion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
