# Generated by Django 5.1.4 on 2025-12-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_ticketsettlement_is_partial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada'), ('partially_paid', 'Parcialmente fechada'), ('cancelled', 'Cancelada')], max_length=255),
        ),
    ]
